version: "3.9"

services:
  app:
    build: .
    container_name: clean-code
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=golang
      - DB_PASSWORD=golang
      - DB_NAME=game_db
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    depends_on:
      - db

  db:
    image: postgres:17.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
